spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    com.hospital: DEBUG
    org.springframework.security: DEBUG

